/** @module calcost/constants
 *
 * @copyright Michael McCarthy <michael.mccarthy@ieee.org> 2017
 * @license MIT
 */

'use strict';

module.exports = Object.freeze({

  /** FIXME */
  RATETYPE_MIN_VALUE: 0,
  RATETYPE_PER_MILLISECOND: 0,
  RATETYPE_PER_SECOND_FRACTIONAL: 10,
  RATETYPE_PER_SECOND_ROUNDUP: 11,
  RATETYPE_PER_HOUR_FRACTIONAL: 20,
  RATETYPE_PER_HOUR_ROUNDUP: 21,
  RATETYPE_PER_HOUR_TOUCHED: 22,
  RATETYPE_PER_DAY_FRACTIONAL: 30,
  RATETYPE_PER_DAY_ROUNDUP: 31,
  RATETYPE_PER_DAY_TOUCHED: 32,
  RATETYPE_PER_DAY_FRACTIONAL: 40,
  RATETYPE_PER_DAY_ROUNDUP: 41,
  RATETYPE_PER_DAY_TOUCHED: 42,
  RATETYPE_MAX_VALUE: 42
});
